### ISSUE TITLE
Missing plays

### ISSUE THREAD

**Issue by lucagiovannini7** [dracor-org/epdracor-sources#2]
Scrolling through Early Print, I realised that some plays are missing from our EPDraCor import. Apparently, our initial lists included only plays which were transcribed from the Early English Books Online (EEBO, ep-id starting with "A") database, while missing the ones from the Eighteenth-Century Collections Online (ECCO, ep-id starting with "C"). In other terms, we are missing a (relatively) minor share of plays from ca. 1700 onwards. For example, we have the EEBO version of Susannah Centlivre's _The Perjured Husband, or The Adventures of Venice_ [A31469](https://texts.earlyprint.org/works/A31469.xml), but not its ECCO version [C34280](https://texts.earlyprint.org/works/C34280.xml).

Anyway, if I wanted to manually add some files to the corpus and work on them with the who-is tool, is it enough to download the  .xmls from EP and add them to [epdracor-sources](https://github.com/dracor-org/epdracor-sources/xml/)? Will they be picked up automatically by the workflow?

**Comment by cmil** [comment]
@lucagiovannini7 I added some documentation on how to add new plays to `epdracor` and `epdracor-sources`, see https://github.com/dracor-org/epdracor#adding-new-plays-to-the-repo. As you can see, there are several steps involved. And for making new plays available in _epdracor-whois_ additional steps would be required to create the JSON input this tool needs, which is not yet documented.

If you would add the IDs of the ECCO/EEBO plays you need to this repo's [ids.txt](https://github.com/dracor-org/epdracor-sources/blob/main/ids.txt) as well as to _epdracor's_ [index.xml](https://github.com/dracor-org/epdracor/blob/main/index.xml), I could assist you with running the scripts and updating _epdracor-whois_.

Should we in this context also think about consolidating the selection of plays for the corpus as a whole (see dracor-org/epdracor#34)?

**Comment by lucagiovannini7** [comment]
Thanks! I'm adding two plays I need for my project ([C14220](https://texts.earlyprint.org/works/C14220) and [C03530](https://texts.earlyprint.org/works/C03530)) as a test.
