### ISSUE TITLE
Improving titles in the vanilla corpus

### ISSUE THREAD

**Issue by lucagiovannini7** [dracor-org/epdracor-sources#4]
While most titles of the plays in the [vanilla corpus](https://staging.dracor.org/ep) are short and human-readable, some of them display longer and cumbersome names, including author name, genre, company, theatre, etc. 

For example, [ep000676](https://staging.dracor.org/api/corpora/ep/play/pix-the-spanish-wives/tei) has _The Spanish wives a farce, as it was acted by His Majesty's servants at the theatre in Dorset-Garden_, instead of _The Spanish wives_. 

Am I allowed to change the title in the original source .xml [here](https://github.com/dracor-org/epdracor-sources/blob/main/xml/A54960.xml) to improve readability and coherence with the other corpora? After all, even the Early Print display name was the shorter one (see `<ep:title>` element).

Note: sometimes it also depends from the structure of the source .xml. [ep000835](https://staging.dracor.org/api/corpora/ep/play/shakespeare-king-lear/tei), for example, has two `<title>` elements in `<titleStmt>`, first the long one and then the short one.

**Comment by peertrilcke** [comment]
Hm, early print has different solutions for that, right? E.g. a short title in the `<fileDesc>` `<titleStmt>`, the full title in the `<sourceDesc>` `<titleStmt>`, and so on. 

Maybe we could add `type=short` (https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-titlePart.html)?

But I do not have a strong opinion on that. maybe @ingoboerner has a better informed idea?

**Comment by lucagiovannini7** [comment]
They have, but seemingly they are not consistent in the `<fileDesc>` : for example, Pix' [Spanish wives](https://raw.githubusercontent.com/dracor-org/epdracor-sources/main/xml/A54960.xml) has the longer title there, while Greville's [Mustapha](https://raw.githubusercontent.com/dracor-org/epdracor-sources/main/xml/A02227.xml) has the shorter one, and so on. Since the majority of the vanilla corpus displays the shorter one, which is definitely more convenient, I would opt for that, and I think your suggestion of adding `type="short"` could work fine.

**Comment by cmil** [comment]
Since the problem at hand seems to be what title we want to display in DraCor and since the EarlyPrint sources are not consistent in how the provide convenient short titles, I would suggest not to try to correct the sources but override them in our workflow where necessary.  To do that we could introduce `title` and maybe also `subtitle` attributes to the index.xml.

**Comment by cmil** [comment]
@lucagiovannini7 See the above PR. I changed the transformation to prefer the `ep:title`. Where this does not yield the desired result you could now override the title by specifying one in [epdracor's index.xml](https://github.com/dracor-org/epdracor/blob/main/index.xml).

**Comment by cmil** [comment]
I also updated https://staging.dracor.org/ep with the files from the [enhance-titles branch](https://github.com/dracor-org/epdracor/tree/enhance-titles).

**Comment by lucagiovannini7** [comment]
> @lucagiovannini7 See the above PR. I changed the transformation to prefer the `ep:title`. Where this does not yield the desired result you could now override the title by specifying one in [epdracor's index.xml](https://github.com/dracor-org/epdracor/blob/main/index.xml). Would this be a sufficient solution?

Yes, I think it's the best solution, thanks!

**Comment by cmil** [comment]
@lucagiovannini7 Great. I merged the PR.
